on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  lint:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint.yaml@main"

  build:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-build.yaml@main"

  test:
    needs: ["lint", "build"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test.yaml@main"
    with:
      foundry-fuzz-runs: 5000
      foundry-profile: "test"
      match-path: "test/**/*.sol"

  release-artifacts:
    needs: ["build"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-release.yaml@main"
    strategy:
      matrix:
        contract-name: ["Arbitrum_SpokePool", "Base_SpokePool"]
    with:
      contract-name: ${{ matrix.contract-name }}
      store-artifacts: true
